import { Button } from '@/componenst/button/button';
import ContactListItem from '@/componenst/contact-list-item/contact-list-item';
import { Icon } from '@/componenst/icon';
import Head from 'next/head';
import Image from 'next/image';
import profile_pic from '../../public/assets/images/profile_pic.png';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={`home-screen`}>
                <div className={'header-spacer'}/>

                <div className={'header display-flex justify-content-center'}>
                    <div className={'row align-items-center'}>
                        <Icon
                            icon={'back-arrow'}
                            size={24}
                            wrapperClasses={'p-2 mr-6'}
                        />

                        <div className={'content-wrapper display-flex align-items-center justify-content-between'}>
                            <h1>Contacts</h1>
                            <div className={'display-flex'}>
                                <Icon
                                    icon={'settings'}
                                    size={24}
                                    wrapperClasses={'p-2 mr-2'}
                                />

                                <div className={'p-2 mr-6'}>
                                    <Image
                                        src={profile_pic}
                                        width={24} height={24}
                                    />
                                </div>

                                <Button
                                    icon={<Icon
                                        icon={'add'}
                                        size={24}
                                        wrapperClasses={'mr-2'}
                                    />}

                                    type={'special'}
                                    title={'Add new'}
                                    onClick={() => console.log('new has been added')}
                                />
                            </div>
                        </div>

                        <Icon
                            icon={'light-mode'}
                            size={24}
                            wrapperClasses={'p-2 ml-6'}
                        />
                    </div>
                </div>

                <div className={'display-flex justify-content-center'}>
                    <div className={'content-wrapper'}>
                        <ContactListItem name={'me'} phone={'+ 36 30 123 4567'}/>
                    </div>
                </div>
            </main>
        </>
    );
}
